name: untitled
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1
  firebase_database: ^11.2.0
  fl_chart: ^0.69.2
  intl: ^0.20.1
  http: ^1.2.2
  cupertino_icons: ^1.0.2
  xml: ^6.2.2
  collection: ^1.16.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
